name: ChatPlugin
version: 2.0.0-SNAPSHOT
main: com.alttd.chat.ChatPlugin
api-version: 1.18
authors: [Destro, Teriuihi]
depend: [LuckPerms]
commands:
  globalchat:
    permission: command.chat.globalchat
    permission-message: You do not have permission!
    aliases: gc
  toggleglobalchat:
    permission: command.chat.globalchat
    permission-message: You do not have permission!
    aliases: togglegc
  message:
    permission: command.chat.message
    aliases: [msg, tell]
  reply:
    permission: command.chat.message
    aliases: r
  continue:
    permission: command.chat.message
    aliases: c
  ignore:
    permission: command.chat.ignore
  unignore:
    permission: command.chat.ignore
  muteserver:
    permission: command.chat.mute-server
  spy:
    permission: command.chat.togglespy
  p:
    permission: command.chat.p
  chatclear:
    permission: chat.command.clear-chat
  emoteslist:
    permission: chat.command.emoteslist
    aliases: [emotes]
  nick:
    permission: chat.command.nick