name: ChatPlugin
version: ${project.version}
main: com.alttd.chat.ChatPlugin
api-version: 1.16
authors: [Destro, Teriuihi]
depend: [LuckPerms]
commands:
  globalchat:
    permission: command.globalchat
    permission-message: You do not have permission!
    aliases: gc
  message:
    permission: command.message
    aliases: msg
  reply:
    permission: command.message
    aliases: r