name: ChatPlugin
version: ${project.version}
main: com.alttd.chat.ChatPlugin
api-version: 1.16
authors: [Destro, Teriuihi]
depend: [LuckPerms]
commands:
  globalchat:
    permission: command.chat.globalchat
    permission-message: You do not have permission!
    aliases: gc
  toggleglobalchat:
    permission: command.chat.globalchat
    permission-message: You do not have permission!
    aliases: togglegc
  message:
    permission: command.chat.message
    aliases: [msg, tell]
  reply:
    permission: command.chat.message
    aliases: r
  ignore:
    permission: command.chat.ignore
  unignore:
    permission: command.chat.ignore
  muteserver:
    permission: command.chat.mute-server
  spy:
    permission: command.chat.togglespy
  chatparty:
    permission: command.chat.chatparty
  pc:
    permission: command.chat.pc